// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartInsights.Infrastructure.Data;

#nullable disable

namespace SmartInsights.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartInsights.Domain.Entities.AIUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<double>("Cost")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Operation");

                    b.HasIndex("Operation", "CreatedAt");

                    b.ToTable("AIUsageLogs");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Input", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AIProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("ClarityPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HelpfulnessPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("ImportancePct")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("InquiryId")
                        .HasColumnType("uuid");

                    b.Property<double?>("QualityPct")
                        .HasColumnType("double precision");

                    b.Property<bool?>("RevealApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("RevealRequested")
                        .HasColumnType("boolean");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Sentiment")
                        .HasColumnType("text");

                    b.Property<int?>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tone")
                        .HasColumnType("text");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("UrgencyPct")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InquiryId");

                    b.HasIndex("Sentiment");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("ThemeId");

                    b.HasIndex("TopicId");

                    b.HasIndex("Type");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("InquiryId", "Status")
                        .HasDatabaseName("IX_Inputs_InquiryId_Status");

                    b.HasIndex("Status", "AIProcessedAt")
                        .HasDatabaseName("IX_Inputs_Status_AIProcessedAt");

                    b.HasIndex("TopicId", "CreatedAt")
                        .HasDatabaseName("IX_Inputs_TopicId_CreatedAt");

                    b.HasIndex("Type", "Status", "CreatedAt")
                        .HasDatabaseName("IX_Inputs_Type_Status_CreatedAt");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InputReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InputId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InputId");

                    b.HasIndex("UserId");

                    b.HasIndex("InputId", "CreatedAt");

                    b.ToTable("InputReplies");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SummaryGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Inquiries_Status_CreatedAt");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InquiryDepartment", b =>
                {
                    b.Property<Guid>("InquiryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("InquiryId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("InquiryDepartments");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InquiryProgram", b =>
                {
                    b.Property<Guid>("InquiryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("InquiryId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("InquiryPrograms");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InquirySemester", b =>
                {
                    b.Property<Guid>("InquiryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.HasKey("InquiryId", "SemesterId");

                    b.HasIndex("SemesterId");

                    b.ToTable("InquirySemesters");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SummaryGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProgramId");

                    b.HasIndex("Role");

                    b.HasIndex("SemesterId");

                    b.HasIndex("Status");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Input", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.Inquiry", "Inquiry")
                        .WithMany("Inputs")
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartInsights.Domain.Entities.Theme", "Theme")
                        .WithMany("Inputs")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartInsights.Domain.Entities.Topic", "Topic")
                        .WithMany("Inputs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartInsights.Domain.Entities.User", "User")
                        .WithMany("Inputs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inquiry");

                    b.Navigation("Theme");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InputReply", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.Input", "Input")
                        .WithMany("Replies")
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInsights.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Input");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Inquiry", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedInquiries")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InquiryDepartment", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.Department", "Department")
                        .WithMany("InquiryDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInsights.Domain.Entities.Inquiry", "Inquiry")
                        .WithMany("InquiryDepartments")
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InquiryProgram", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.Inquiry", "Inquiry")
                        .WithMany("InquiryPrograms")
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInsights.Domain.Entities.Program", "Program")
                        .WithMany("InquiryPrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquiry");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.InquirySemester", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.Inquiry", "Inquiry")
                        .WithMany("InquirySemesters")
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInsights.Domain.Entities.Semester", "Semester")
                        .WithMany("InquirySemesters")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquiry");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Topic", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.Department", "Department")
                        .WithMany("Topics")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.User", b =>
                {
                    b.HasOne("SmartInsights.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartInsights.Domain.Entities.Program", "Program")
                        .WithMany("Users")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartInsights.Domain.Entities.Semester", "Semester")
                        .WithMany("Users")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Program");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Department", b =>
                {
                    b.Navigation("InquiryDepartments");

                    b.Navigation("Topics");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Input", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Inquiry", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("InquiryDepartments");

                    b.Navigation("InquiryPrograms");

                    b.Navigation("InquirySemesters");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Program", b =>
                {
                    b.Navigation("InquiryPrograms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Semester", b =>
                {
                    b.Navigation("InquirySemesters");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Theme", b =>
                {
                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("SmartInsights.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedInquiries");

                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
